### ISSUE TITLE
error Optional("The operation couldn’t be completed. (MSALErrorDomain error -50000.)")

### ISSUE THREAD

**Issue by ljunquera** [arbyruns/SwiftUI-MSALSample#1]
I seem to be making some progress but am now stuck on this error:

`error Optional("The operation couldn’t be completed. (MSALErrorDomain error -50000.)")`

I changed only:
- clientID
- redirectUri
- scopes

I used your Info.plist. I did not change the:
- MSALB2CAuthority url, but did try with the Application ID URI from Azure

**Comment by arbyruns** [comment]
Do you  get the MSAL signin alert or does it fail even before that?

**Comment by ljunquera** [comment]
When I open the view:

makeUIViewController(context:)
init(viewModel:)
viewDidLoad()
loadMSALScreen()
error Optional("The operation couldn’t be completed. (MSALErrorDomain error -50000.)")
updateUIViewController(_:context:)
makeUIViewController(context:)
init(viewModel:)
viewDidLoad()
loadMSALScreen()
error Optional("The operation couldn’t be completed. (MSALErrorDomain error -50000.)")
updateUIViewController(_:context:)

**Comment by arbyruns** [comment]
Hmm that could be a reherring.  What happens when you tap `Login with MSAL`?  Also, what is the bundleID you used when you registered your app in Azure?  It should have been `com.arby.SwiftUIMSAL`

**Comment by ljunquera** [comment]
loadMSALScreen()
error Optional("The operation couldn’t be completed. (MSALErrorDomain error -50000.)")
2022-01-14 06:36:22.259729-0500 MyTestApp[74752:1749617] [BackgroundTask] Background Task 1 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by ljunquera** [comment]
Rebuilt project and created new issue to be more precise in the problem.
